jobs:
  - job: WebBuildDeploy
    displayName: Web > Build, Test
    steps:
      - checkout: self
        fetchDepth: 0
      - template: ../steps/terraform-init.yml
      - template: ../steps/get-infra-output.yml      
      - template: ../steps/build-web.yml
      - template: ../steps/test-web.yml
      - template: ../steps/publish-web.yml
