name: "prod-build-release"

trigger: none

pool:
  vmImage: "ubuntu-latest"

schedules:
  - cron: "0 9 * * *"
    displayName: Nightly 10AM UTC (1AM PST) Prod Build-Release
    branches:
      include:
        - main

variables:
  - template: variables.yml
  - group: "build-verification"
  - group: "prod-variables"

stages:
  - template: ./templates/stages/build-release.yml
    parameters:
        environment: Production
