parameters:
    - name: path
      type: string
      default: ""

steps:
    - task: NodeTool@0
      inputs:
          versionSpec: "18.x"
      displayName: Set Node version

    - task: Cache@2
      inputs:
          key: 'npm | "$(Agent.OS)" | "${{ parameters.path }}/package-lock.json"'
          restoreKeys: |
              npm | "$(Agent.OS)"
          path: $(npm_config_cache)
      displayName: Cache npm
